package com.threedreport.app.platform

import com.threedreport.core.slicer.GCodeMetadataParser
import java.io.File
import kotlin.io.path.createTempDirectory
import kotlin.test.Test
import kotlin.test.assertEquals
import kotlin.test.assertIs
import kotlin.test.assertTrue

/**
 * Um G-code de centenas de MB é lido só pelas pontas (decisão 108), onde os fatiadores gravam os
 * metadados. O rodapé abaixo é o do PrusaSlicer 2.4 (ver `RealGCodeFixtures` no core).
 */
class GCodeReadTest {

    private val prusaFooter = """
        ; filament used [mm] = 215.44
        ; filament used [cm3] = 0.52
        ; filament used [g] = 0.54
        ; total filament used [g] = 0.54
        ; estimated printing time (normal mode) = 8m 56s
        ; filament_type = ABS
        ; printer_model = Voron 2.4 350
    """.trimIndent()

    @Test
    fun aHugeFileIsReadOnlyByItsEdgesAndStillGivesTheMetadata() {
        val file = File(createTempDirectory("3dreport-gcode").toFile(), "grande.gcode")
        file.bufferedWriter().use { out ->
            out.write("; generated by PrusaSlicer 2.4.0\n")
            // ~20 MB de movimento, que não interessa pro orçamento.
            val move = "G1 X123.456 Y78.901 E0.02345 F1800\n"
            repeat(20_000_000 / move.length) { out.write(move) }
            out.write(prusaFooter)
            out.write("\n")
        }

        val bytes = DesktopPlatform.readGCodeForMetadata(file)
        assertTrue(bytes.size < 10 * 1024 * 1024, "leu ${bytes.size} bytes de ${file.length()}")

        val metadata = GCodeMetadataParser.parse(bytes.decodeToString())
        assertEquals(0.21544, metadata.filamentLengthMeters!!, 1e-9)
        assertEquals(8 + 56.0 / 60, metadata.printTimeMinutes!!, 1e-6)
        assertEquals("Voron 2.4 350", metadata.printerModel)
    }

    @Test
    fun aFileThatDisappearedIsAMessageAndNotACrash() {
        val result = DesktopPlatform.readPicked(File("/nao/existe/peca.gcode"), FileKind.GCODE)

        assertIs<PickResult.Failed>(result)
    }
}
