package com.threedreport.core.slicer

import kotlin.io.encoding.Base64
import kotlin.io.encoding.ExperimentalEncodingApi
import kotlin.test.Test
import kotlin.test.assertEquals
import kotlin.test.assertNull
import kotlin.test.assertTrue

@OptIn(ExperimentalEncodingApi::class)
class GCodeMetadataParserTest {

    @Test
    fun parsesPrusaSlicerStyleComments() {
        val gcode = """
            ; generated by PrusaSlicer
            G28
            ; filament used [mm] = 1234.56
            ; filament used [cm3] = 2.97
            ; filament used [g] = 3.68
            ; estimated printing time (normal mode) = 1h 23m 45s
        """.trimIndent()

        val metadata = GCodeMetadataParser.parse(gcode)

        assertEquals(1.23456, metadata.filamentLengthMeters!!, 0.0001)
        assertEquals(83.75, metadata.printTimeMinutes!!, 0.0001)
    }

    @Test
    fun parsesBambuStudioStyleComments() {
        val gcode = """
            ; total filament length [mm] : 5000.00
            ; total estimated time: 2h30m
        """.trimIndent()

        val metadata = GCodeMetadataParser.parse(gcode)

        assertEquals(5.0, metadata.filamentLengthMeters!!, 0.0001)
        assertEquals(150.0, metadata.printTimeMinutes!!, 0.0001)
    }

    @Test
    fun parsesCuraStyleComments() {
        val gcode = """
            ;FLAVOR:Marlin
            ;Filament used: 3.5m
            ;TIME:5025
        """.trimIndent()

        val metadata = GCodeMetadataParser.parse(gcode)

        assertEquals(3.5, metadata.filamentLengthMeters!!, 0.0001)
        assertEquals(5025.0 / 60.0, metadata.printTimeMinutes!!, 0.0001)
    }

    @Test
    fun sumsMultipleExtrudersForFilamentUsed() {
        val gcode = "; filament used [mm] = 1000.0, 500.0"

        val metadata = GCodeMetadataParser.parse(gcode)

        assertEquals(1.5, metadata.filamentLengthMeters!!, 0.0001)
    }

    @Test
    fun returnsEmptyMetadataWhenNothingRecognized() {
        val gcode = "G28\nG1 X10 Y10\n; just a random comment"

        val metadata = GCodeMetadataParser.parse(gcode)

        assertNull(metadata.filamentLengthMeters)
        assertNull(metadata.printTimeMinutes)
        assertNull(metadata.thumbnail)
        assertTrue(metadata.isEmpty)
    }

    @Test
    fun parsesThumbnailAndPicksTheLargestWhenMultiplePresent() {
        val smallPayload = "small-thumbnail".encodeToByteArray()
        val bigPayload = "much-bigger-thumbnail-payload-data".encodeToByteArray()
        val gcode = """
            ; thumbnail begin 16x16 999
            ; ${Base64.encode(smallPayload)}
            ; thumbnail end
            ; thumbnail begin 220x124 999
            ; ${Base64.encode(bigPayload)}
            ; thumbnail end
        """.trimIndent()

        val thumbnail = GCodeMetadataParser.parse(gcode).thumbnail

        assertEquals("png", thumbnail?.fileExtension)
        assertTrue(thumbnail!!.bytes.contentEquals(bigPayload))
    }

    @Test
    fun detectsJpegThumbnailVariant() {
        val payload = "jpeg-thumbnail-bytes".encodeToByteArray()
        val gcode = """
            ; thumbnail_JPG begin 300x300 123
            ; ${Base64.encode(payload)}
            ; thumbnail_JPG end
        """.trimIndent()

        val thumbnail = GCodeMetadataParser.parse(gcode).thumbnail

        assertEquals("jpg", thumbnail?.fileExtension)
        assertTrue(thumbnail!!.bytes.contentEquals(payload))
    }
}
