package com.threedreport.core.slicer

/**
 * Trechos de G-codes **reais**, exportados pelos próprios fatiadores e publicados em repositórios
 * abertos (a origem de cada um está no comentário). Só as linhas de comentário que o parser lê
 * foram copiadas, sem os comandos de movimento e sem a miniatura. Existem pra que o parser não
 * dependa de formato imaginado (mesma disciplina das decisões 55, 56 e 89): foi um arquivo destes
 * que mostrou que o tempo do Bambu Studio 2.x não era lido.
 */
object RealGCodeFixtures {

    /** Bambu Studio 02.04.00.70, Bambu Lab A1 mini, TPU. github.com/Hzhao-ocad/GcodeUnExtruder (plate_1.gcode, commit ee4e0b4) */
    val BAMBU_STUDIO_A1_MINI = """
; BambuStudio 02.04.00.70
; model printing time: 1m 6s; total estimated time: 9m 3s
; total filament length [mm] : 75.74
; filament_colour = #00AE42
; filament_settings_id = "Generic TPU @BBL A1M -thesis test160"
; filament_type = TPU
; filament_vendor = Generic
; layer_height = 0.28
; printer_model = Bambu Lab A1 mini
; printer_settings_id = Bambu Lab A1 mini 0.4 nozzle
; sparse_infill_density = 15%
""".trimIndent()

    /** Bambu Studio 02.03.01.51, Bambu Lab X1 Carbon, PLA. github.com/malekgxd/slicercompare (temp/plate_1.gcode, commit 17eb372) */
    val BAMBU_STUDIO_X1C = """
; BambuStudio 02.03.01.51
; model printing time: 4m 48s; total estimated time: 11m 36s
; total filament length [mm] : 325.49
; filament_colour = #00AE42
; filament_settings_id = "Bambu PLA Basic @BBL X1C"
; filament_type = PLA
; filament_vendor = (Undefined)
; layer_height = 0.2
; printer_model = Bambu Lab X1 Carbon
; printer_settings_id = Bambu Lab X1 Carbon 0.4 nozzle
; sparse_infill_density = 20%
""".trimIndent()

    /** OrcaSlicer 1.6.3, Voron 2.4 350, ASA. github.com/valadas/em-calibrator-postprocessor (samples/orca-slicer.gcode, commit e239351) */
    val ORCA_SLICER_VORON = """
; generated by OrcaSlicer 1.6.3 on 2023-07-11 at 19:15:28
; filament used [mm] = 2932.98
; filament used [cm3] = 7.05
; filament used [g] = 7.34
; filament cost = 0.26; total filament used [g] = 7.34
; estimated printing time (normal mode) = 8m 0s
; filament_colour = #F2754E
; filament_settings_id = "Sparta ASA"
; filament_type = ASA
; filament_vendor = Generic
; layer_height = 0.3
; printer_model = Voron 2.4 350
; printer_settings_id = Voron 2.4 350 0.6 nozzle
; sparse_infill_density = 40%
""".trimIndent()

    /** PrusaSlicer 2.4.0-alpha1, perfil de Voron vindo de um .3mf, ABS. github.com/kageurufu/preprocess_cancellation (GCode/prusaslicer.gcode, commit 3b9cf64) */
    val PRUSA_SLICER_VORON = """
; generated by PrusaSlicer 2.4.0-alpha1+win64 on 2021-09-03 at 16:52:36 UTC
; filament used [mm] = 215.44
; filament used [cm3] = 0.52
; filament used [g] = 0.54
; total filament used [g] = 0.54
; estimated printing time (normal mode) = 8m 56s
; filament_colour = #A768DF
; filament_settings_id = "test_bed.3mf (KVP ABS @VORON - Copy)"
; filament_type = ABS
; filament_vendor = (Unknown)
; fill_density = 42%
; layer_height = 0.2
; printer_model = Voron_v2_300_aferburner
; printer_settings_id = test_bed.3mf (Voron_v2_300_afterburner 0.4 nozzle - Copy)
""".trimIndent()

    /** Cura 5.3.1, Creality Ender-3 V2. github.com/mriscoc/Ender3V2S1 (slicer scripts/cura/SimpleCuraTest.gcode, commit 05903a8) */
    val CURA_ENDER3_V2 = """
;FLAVOR:Marlin
;TIME:420
;Filament used: 0.329575m
;Generated with Cura_SteamEngine 5.3.1
;SETTING_3 {"global_quality": "[general]\\nversion = 4\\nname = Low Quality #2\\
;SETTING_3 ndefinition = creality_ender3\\n\\n[metadata]\\ntype = quality_change
;SETTING_3 s\\nquality_type = low\\nsetting_version = 21\\n\\n[values]\\nacceler
;SETTING_3 ation_enabled = True\\nadhesion_type = skirt\\nbridge_settings_enable
;SETTING_3 d = True\\njerk_enabled = True\\nmachine_firmware_retract = True\\nma
;SETTING_3 chine_name = Creality Ender-3 V2\\nsupport_enable = False\\nsupport_s
;SETTING_3 tructure = tree\\n\\n", "extruder_quality": ["[general]\\nversion = 4
;SETTING_3 \\nname = Low Quality #2\\ndefinition = creality_ender3\\n\\n[metadat
;SETTING_3 a]\\ntype = quality_changes\\nquality_type = low\\nsetting_version = 
;SETTING_3 21\\nposition = 0\\n\\n[values]\\nbrim_outside_only = False\\nbrim_wi
;SETTING_3 dth = 2\\ncoasting_enable = True\\nfill_outline_gaps = True\\ninfill_
;SETTING_3 before_walls = True\\ninfill_enable_travel_optimization = True\\ninfi
;SETTING_3 ll_overlap = 20\\nironing_only_highest_layer = True\\nmaterial_print_
;SETTING_3 temperature = 195\\nmaterial_print_temperature_layer_0 = 200\\noptimi
;SETTING_3 ze_wall_printing_order = False\\nretract_at_layer_change = True\\nski
;SETTING_3 rt_line_count = 2\\nspeed_layer_0 = 15\\nsupport_angle = 65\\nsupport
;SETTING_3 _infill_rate = 10\\nz_seam_type = sharpest_corner\\n\\n"]}
""".trimIndent()
}
